export interface GralResponse{
    status:  number;
    message: string;
    errors?: string | null;
}
//DASHBOARD

export interface Overview {
    user: OverviewUser;
    pages: OverviewPages[];
}

export interface OverviewUser {
    name: string;
    surname: string;
    role: string;
    email: string;
    picturepath: string;
}

export interface OverviewPages {
    title: string;
    icon?: string;
    permalink?: string;
    action?: () => void;
}
/**GESTOR */
//PROMOTIONS
export interface createcampaing {
    name: string;
    begin_date: string;
    end_date: string;
    description: string;
    segment_name: string;
    category:     string;
    visitis:      number | null;
}


export interface GetcampaingResponse extends GralResponse{
    data:    Data;
}

export interface DeleteVehicleImage {
    status:  string;
    code:    string;
    message: string;
}

export interface DeleteCampaign {
    status:  string;
    code:    string;
    message: string;
}

export interface Data {
    campaigns: Campaign[];
}

export interface Campaign {
    uuid:        string;
    begin_date:  Date | string;
    end_date:    Date | string;
    name:        string;
    description: string;
    image_path:  null;
    created_at:  Date;
    promotions:  any[];
    promo_Path: string;
    category:   string;
    segment_name: string;
    visitis:    null | number;
}

export interface menu{
    name:       string;
    uuid:       string;
}

export interface UploadImages {
    status:  number;
    message: string;
    data:    null;
}

export interface ImageOrder {
    id:         number;
    path:       string;
    legal:      string;
 }

 export interface GetPromotionsByBrand {
    status:     string;
    code:       number;
    promotions: Promotion[];
    paths:      string[];
}

export interface Promotion {
    id:         number;
    path:       string;
    brand:      string;
    legal:      string;
    status:     string;
    created_at: string;
    updated_at: string;
    spec_sheet: string;
}

export interface ImageOrderPromo {
    id:         number;
    uuid:       any;
    path:       string;
    external_website: string | null;
 }

 export interface Camp {
    sort_id:        string;
    uuid:           string;
    name:           string;
    description:    string;
    image_path:     string;
    created_at:     Date | string;
    spec_sheet:     string;
}

/** STAFF */

export interface tableD {
    id: number,
   name: string,
}

/** GET EVENTS */
export interface GetEvents {
    code:   number;
    status: string;
    events: Evento[];
}

export interface Evento {
    id:         number;
    title:      string;
    subtitle:      string;
    path:       string;
    brand:      null;
    type:       string;
    status:     string;
    event_date: Date;
    detail:     null;
    event_images: EventImage[];
    created_at: Date;
    updated_at: Date;
}

export interface EventImage {
    id:         number;
    path:       string;
    event_id:   number;
    created_at: Date;
    updated_at: Date;
  }

  // Generated by https://quicktype.io

export interface GetPromotionsByBrand {
    status:     string;
    code:       number;
    promotions: Promotion[];
    paths:      string[];
}

export interface Promotion {
    id:         number;
    path:       string;
    brand:      string;
    legal:      string;
    status:     string;
    created_at: string;
    updated_at: string;
}

export interface ImageOrder {
    id:         number;
    path:       string;
    legal:      string;
 }

 export interface GetcampaingResponse {
    status:  number;
    message: string;
    data:    Data;
}

export interface Data {
    campaigns: Campaign[];
}

export interface Campaign {
    uuid:        string;
    begin_date:  Date | string;
    end_date:    Date | string;
    name:        string;
    description: string;
    image_path:  null;
    created_at:  Date;
    promotions:  any[];
    promo_Path: string;
}

export interface Camp {
    sort_id:        string;
    uuid:           string;
    name:           string;
    description:    string;
    image_path:     string;
    spec_sheet:     string;
    created_at:     Date | string;
    legal:          string;
}

export interface UploadVideo {
    status:  string;
    code:    string;
    message: string;
    event:   Event;
}

export interface Event {
    title:      string;
    status:     string;
    type:       string;
    event_date: Date;
    path:       string;
    updated_at: Date;
    created_at: Date;
    id:         number;
}
export interface DeleteEvent {
    code:   number;
    status: string;
    message: string;
}
export interface CreateEvent {
    status:  string;
    code:    string;
    message: string;
    event:   Event;
}

export interface Event {
    title:      string;
    status:     string;
    brand:      string;
    type:       string;
    event_date: Date;
    path:       string;
    updated_at: Date;
    created_at: Date;
    id:         number;
}

export interface UploadEventImages {
    status:  string;
    code:    string;
    message: string;
    event:   Event;
}

export interface Event {
    id:           number;
    title:        string;
    subtitle:     string;
    description:  string;
    path:         string;
    brand:        string;
    type:         string;
    status:       string;
    event_date:   Date;
    detail:       null;
    created_at:   Date;
    updated_at:   Date;
    event_images: EventImage[];
}

export interface EventImage {
    id:         number;
    path:       string;
    event_id:   number;
    created_at: Date;
    updated_at: Date;
}
export interface ChangeOrder {
    status:         string;
    code:           string;
    message:        string;
}

export interface LoadImages {
    status:  string;
    code:    string;
    message: string;
    vehicle: Vehicle;
}

export interface Vehicle {
    id:              number;
    name:            string;
    description:     string;
    vin:             string;
    location:        string;
    yearModel:       number;
    purchaseDate:    Date;
    price:           number;
    priceList:       number;
    salePrice:       number;
    priceBond:       null;
    type:            string;
    carline:         string;
    cylinders:       number;
    colorInt:        string;
    colorExt:        string;
    status:          string;
    plates:          null;
    transmission:    string;
    inventoryDays:   number;
    km:              number;
    numKeys:         number;
    studs:           Extinguiser;
    spareTire:       Extinguiser;
    hydraulicJack:   Extinguiser;
    extinguiser:     Extinguiser;
    reflectives:     Extinguiser;
    handbook:        Extinguiser;
    insurancePolicy: Extinguiser;
    powerCables:     Extinguiser;
    promotion:       null;
    priceOffer:      null;
    carmodel_id:     number;
    vehiclebody_id:  number;
    branch_id:       number;
    created_at:      Date;
    updated_at:      Date;
    deleted_at:      null;
    vehicle_images:  VehicleImage[];
}

export enum Extinguiser {
    No = "no",
    Yes = "yes",
}

export interface VehicleImage {
    id:               number;
    path:             string;
    external_website: Extinguiser;
    vehicle_id:       number;
    created_at:       Date;
    updated_at:       Date;
}


//riders
export interface RiderResponse {
    status:  number;
    message: string;
    data:    DataRider;
}

export interface CustomerResponse {
    status:  number;
    message: string;
    data:    DataCustomer;
}

export interface DataRider {
    riders: PagesRider;
}


export interface DataCustomer {
    clientes: PagesCustomer;
}
export interface PagesRider {
    current_page:   number;
    data:           Rider[];
    first_page_url: string;
    from:           number;
    last_page:      number;
    last_page_url:  string;
    links:          Link[];
    next_page_url:  null;
    path:           string;
    per_page:       number;
    prev_page_url:  null;
    to:             number;
    total:          number;
}

export interface PagesCustomer {
    current_page:   number;
    data:           CustomerSale[];
    first_page_url: string;
    from:           number;
    last_page:      number;
    last_page_url:  string;
    links:          Link[];
    next_page_url:  null;
    path:           string;
    per_page:       number;
    prev_page_url:  null;
    to:             number;
    total:          number;
}

export interface Rider {
    reward_uuid:        string;
    reward_name:        string;
    reward_description: string;
    customer_uuid:      string;
    user_nickname:      string;
    customer_name:      string;
    customer_last_name: string;
    customer_email:     string;
    customer_dealership:string;
    customer_size:      string;
    vehicle_uuid:       string;
    vehicle_vin:        string;
    vehicle_mileage:    number;
    total_points:       number;
    status:             null | string;
    customer_phone:     string;
    reward_created_date:Date;
    customer_reward_uuid:string;
    vehicle_model:      string;
    initial_mileage:    number;
    final_mileage:      number;
    vehicle_year:       string;
}


export interface CustomerSale {
    customer_uuid:      string;
    user_nickname:      string;
    customer_name:      string;
    customer_last_name: string;
    customer_email:     string;
    total_points:       number;
    customer_phone:     string;
}

export interface Link {
    url:    null | string;
    label:  string;
    active: boolean;
}

export interface User {
    nickname: string;
}

export interface tableData {
    vehicle_uuid: string;
    id: number;
    name: string;
    kilometraje: number;
    puntos: number;
    customer: string;
    reward_uuid: string;
}

export interface tableCustomersData {
    id: number;
    name: string;
    puntos: number;
    customer_uuid: string;
    email:string;
    telefono: string;
    color: string;
}

export interface rewardsResponse extends GralResponse{
    data:    DataReward;
}

export interface DataReward {
    rewards: Reward[];
}

export interface Reward {
    uuid:        string;
    name:        string;
    description: string;
    begin_date:  Date;
    end_date:    Date;
    category:    Category;
    type:        string;
    image_path:  null | string;
    created_at:  Date;
}

export enum Category {
    Ride = "ride",
}

export interface rewardTable{
    uuid: string;
    id: number;
    name: string;
    description: string;
    begin_date: string;
    end_date: string;
    // type: string;
}

export interface promosUser{
    name: string;
    url: string;
}

//muestra lla recompensa para poder editarla
export interface detailsRewardResponse {
    status:  number;
    message: string;
    data:    detailsR;
}

export interface detailsR {
    uuid:        string;
    name:        string;
    description: string;
    begin_date:  Date;
    end_date:    Date;
    category:    string;
    type:        null;
    image_path:  null;
    created_at:  Date;
}

//Interfaces para la gestión de usuarios y permisos

export interface UsersResponse extends GralResponse{
    data:    DataUsers;
}

export interface DataUsers {
    current_page:   number;
    data:           Datum[];
    first_page_url: string;
    from:           number;
    last_page:      number;
    last_page_url:  string;
    links:          Link[];
    next_page_url:  null;
    path:           string;
    per_page:       number;
    prev_page_url:  null;
    to:             number;
    total:          number;
}

export interface Datum {
    uuid:       string;
    nickname:   string;
    email:      string;
    created_at: Date;
    role:       string;
    profile:    Profile | null;
}

export interface Profile {
    name:       string;
    last_name:  string;
    gender:     string | null;
    phone_1:    number | null;
    phone_2:    number | null;
    picture:    string | null;
    location:   string | null;
    created_at: Date;
}

export interface userTable {
    nickname:   string;
    email:      string;
    fecha:      Date;
    index:      number;
}

export interface DetailResponsive {
    status:  number;
    message: string;
    data:    DataDetailUser;
}

export interface DataDetailUser {
    user:    UserInfo;
    role:    string;
    profile: Profile;
}

export interface UserInfo {
    uuid:       string;
    nickname:   string;
    email:      string;
    created_at: Date;
}

//interface para extraer los roles
export interface RolesResponse {
    id:         number;
    name:       string;
    guard_name: string;
    created_at: Date;
    updated_at: Date;
}

export interface roles{
    id:         number;
    name:       string;
}

//interfaces para dealership
export interface DealerShipResponse{
    status:  number;
    message: string;
    data:    Dealership[];
}

export interface Dealership {
    name:        string;
    location:    string;
    description: null;
    created_at:  Date;
}


export interface promos{
    created_at:        Date;
    description:        string;
    image_path:         string;
    name:               string;
    sort_id:            number;
    uuid:               string;
}
export interface GetUsersByRol {
    status:  number;
    message: string;
    data:    Data;
}

export interface Data {
    users: UserTechnicians[];
}

export interface UserTechnicians {
    uuid:         string;
    nickname:     string;
    email:        string;
    created_at:   Date;
    user_profile: UserProfile;
}

export interface UserProfile {
    name:       string;
    last_name:  string;
    gender:     null;
    phone_1:    null;
    phone_2:    null;
    picture:    null;
    location:   null;
    created_at: Date;
}
