// Generated by https://quicktype.io
export interface Gral{
    status:      string;
    code:        string;
    message?:     string;
}

 export interface Calendar extends Gral {
    events: Calendary[];
}

export interface Calendary {
    id:         number;
    title:      string;
    description:string;
    path:       string;
    brand:      string;
    type:       string;
    status:     string;
    event_date: string;
    detail:     string;
    created_at: string;
    updated_at: string;
    event_images: EventImage[];
}

export interface EventImage {
    id:         number;
    path:       string;
    event_id:   number;
    created_at: Date;
    updated_at: Date;
}

export interface ImageEventOrder {
    id:            number;
    image:         string;
    title:         string;
    description:   string;
    dateEvent:     string;
    event_images: EventImage[];
 }

 export interface Sheetquote extends Gral{
    sheet_quote: SheetQuote;
    sheet_offer: SheetOffer;
}

export interface SheetQuote {
    body:    string;
    brand:   string;
    model:   string;
    name:    string;
    surname: string;
    email:   string;
    phone:   string;
    buyType: string;
}

export interface SheetOffer extends Gral{
    body:    string;
    brand:   string;
    model:   string;
    name:    string;
    surname: string;
    email:   string;
    phone:   string;
    clientPriceOffer: number;
}

export interface GenerateLead extends Gral{
    lead:    Lead;
}

export interface Lead {
    name:       string;
    surname:    null;
    email:      string;
    phone:      number;
    message:    string;
    updated_at: Date;
    created_at: Date;
    id:         number;
    vehicles:   any[];
}

export interface ReceptionForm extends Gral{
    reception_form: ReceptionFormClass;
}

export interface ReceptionFormClass {
    date:                string;
    hour:                string;
    salesAdvisor:        string;
    brand:               string;
    departureTime:       string;
    visitType:           string;
    visitFirsTime:       string;
    department:          string;
    otherDepartment:     string;
    howFindOut:          string;
    commentaryLead:      string;
    clientName:          string;
    clientAge:           string;
    clientPhone:         string;
    clientEmail:         string;
    preferredMedium:     string;
    model:               string;
    year:                string;
    version:             string;
    color:               string;
    accessories:         string;
    brandSecondOption:   string;
    modelSecondOption:   string;
    versionSecondOption: string;
    colorSecondOption:   string;
    testDrive:           string;
    receivedQuote:       string;
    FAndI:               string;
    leaveCarOnAccount:   string;
    customersCurrentCar: string;
    updated_at:          Date;
    created_at:          Date;
    id:                  number;
}

export interface Brands {
    code: number;
    status: string;
    brands: Branch[];
}

export interface Branch {
    id: number;
    name: string;
    description: null;
    location: null;
    contact: null;
    picture: null;
    created_at: Date;
    updated_at: Date;
}

export interface DataModels {
    code:   number;
    status: string;
    models: Model[];
}

export interface Model {
    id:          number;
    name:        string;
    description: string;
    brand_id:    number;
    created_at:  Date;
    updated_at:  Date;
}

export interface DeleteVehicle{
    status:  string;
    code:    string;
    message: string;
}

export interface DeletedVehicle {
    status:           string;
    deleted_vehicles: DeletedVehicleElement[];
    total:            number;
}

export interface DeletedVehicleElement {
    id:              number;
    name:            string;
    description:     string;
    vin:             string;
    location:        string;
    yearModel:       number;
    purchaseDate:    Date;
    price:           number;
    priceList:       number;
    salePrice:       number;
    type:            string;
    carline:         string;
    cylinders:       number;
    colorInt:        string;
    colorExt:        string;
    status:          string;
    plates:          null;
    transmission:    string;
    inventoryDays:   number;
    km:              number;
    numKeys:         number;
    studs:           string;
    spareTire:       string;
    hydraulicJack:   string;
    extinguiser:     string;
    reflectives:     string;
    handbook:        string;
    insurancePolicy: string;
    powerCables:     string;
    promotion:       null;
    priceOffer:      null;
    carmodel_id:     number;
    vehiclebody_id:  number;
    branch_id:       number;
    created_at:      Date;
    updated_at:      Date;
    deleted_at:      Date;
    vehicle_images:  any[];
}
export interface ChangeStatusVehicle extends Gral{
    update: string;
}
export interface Lead  extends Gral{
    lead:    LeadClass;
}

export interface LeadClass {
    name:       string;
    surname:    string;
    email:      string;
    phone:      number;
    updated_at: Date;
    created_at: Date;
    id:         number;
    vehicles:   Vehicle[];
}

export interface Vehicle {
    id:              number;
    name:            string;
    description:     string;
    vin:             string;
    location:        string;
    yearModel:       number;
    purchaseDate:    Date;
    price:           number;
    priceList:       number;
    salePrice:       number;
    type:            string;
    carline:         string;
    cylinders:       number;
    colorInt:        string;
    colorExt:        string;
    status:          string;
    plates:          null;
    transmission:    string;
    inventoryDays:   number;
    km:              number;
    numKeys:         number;
    studs:           string;
    spareTire:       string;
    hydraulicJack:   string;
    extinguiser:     string;
    reflectives:     string;
    handbook:        string;
    insurancePolicy: string;
    powerCables:     string;
    promotion:       null;
    priceOffer:      null;
    carmodel_id:     number;
    vehiclebody_id:  number;
    branch_id:       number;
    created_at:      Date;
    updated_at:      Date;
    deleted_at:      null;
    pivot:           Pivot;
}

export interface Pivot {
    lead_id:    number;
    vehicle_id: number;
}

